const treeData = [
    {
      user_id: "111",
      name: "foundercode",
      join_by: "0",
      wallet: "110000.00",
      roi_comission: "0.00",
      phone: "7705015444",
      datetime: "2024-11-20 14:02:31",
      level: "0",
      self_payin: 0,
      subordinate_payin: 10965000,
      this_month_payin: "235000",
      children: [
        {
          user_id: "4133",
          name: "ROCKY",
          join_by: "111",
          wallet: "0.00",
          roi_comission: "0.00",
          phone: "7571813329",
          datetime: "2024-11-20 14:06:41",
          level: "1",
          self_payin: "265000",
          subordinate_payin: 10700000,
          this_month_payin: "45000",
          children: [
            {
              user_id: "9237",
              name: "Abhishek Kumar Chaurasiya",
              join_by: "4133",
              wallet: "0.00",
              roi_comission: "0.00",
              phone: "7081006936",
              datetime: "2024-11-20 14:14:29",
              level: "2",
              self_payin: "50000",
              subordinate_payin: 5360000,
              this_month_payin: 0,
              children: [
                {
                  user_id: "2839",
                  name: "Sahodra Devi",
                  join_by: "9237",
                  wallet: "0.00",
                  roi_comission: "0.00",
                  phone: "7522006936",
                  datetime: "2024-11-20 14:16:01",
                  level: "3",
                  self_payin: "20000",
                  subordinate_payin: 2980000,
                  this_month_payin: 0,
                  children: [
                    {
                      user_id: "854",
                      name: "Shivam Jaiswal",
                      join_by: "2839",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "7408088386",
                      datetime: "2024-11-20 14:19:21",
                      level: "4",
                      self_payin: "50000",
                      subordinate_payin: 1100000,
                      this_month_payin: 0,
                      children: [
                        {
                          user_id: "5066",
                          name: "Ayush Jaiswal",
                          join_by: "854",
                          wallet: "0.00",
                          roi_comission: "0.00",
                          phone: "6391929184",
                          datetime: "2024-11-20 14:26:40",
                          level: "5",
                          self_payin: "50000",
                          subordinate_payin: 850000,
                          this_month_payin: 0,
                          children: [
                            {
                              user_id: "6434",
                              name: "Rishabh Pandey",
                              join_by: "5066",
                              wallet: "0.00",
                              roi_comission: "0.00",
                              phone: "7309136704",
                              datetime: "2024-11-20 14:40:23",
                              level: "6",
                              self_payin: "100000",
                              subordinate_payin: 750000,
                              this_month_payin: 0,
                              children: [
                                {
                                  user_id: "9538",
                                  name: "Gula Pandey",
                                  join_by: "6434",
                                  wallet: "0.00",
                                  roi_comission: "0.00",
                                  phone: "6362581932",
                                  datetime: "2024-11-21 15:20:51",
                                  level: "7",
                                  self_payin: "400000",
                                  subordinate_payin: 0,
                                  this_month_payin: "50000",
                                  children: [],
                                },
                                {
                                  user_id: "4450",
                                  name: "Chhote Pandey",
                                  join_by: "6434",
                                  wallet: "0.00",
                                  roi_comission: "0.00",
                                  phone: "9919765679",
                                  datetime: "2024-11-21 15:25:14",
                                  level: "7",
                                  self_payin: "350000",
                                  subordinate_payin: 0,
                                  this_month_payin: "100000",
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          user_id: "1201",
                          name: "Satyam Jaiswal",
                          join_by: "854",
                          wallet: "0.00",
                          roi_comission: "0.00",
                          phone: "8177022557",
                          datetime: "2024-11-20 14:27:49",
                          level: "5",
                          self_payin: "50000",
                          subordinate_payin: 150000,
                          this_month_payin: 0,
                          children: [
                            {
                              user_id: "1371",
                              name: "Urmila Devi",
                              join_by: "1201",
                              wallet: "0.00",
                              roi_comission: "0.00",
                              phone: "7380405180",
                              datetime: "2024-11-21 14:01:13",
                              level: "6",
                              self_payin: "50000",
                              subordinate_payin: 100000,
                              this_month_payin: 0,
                              children: [
                                {
                                  user_id: "6821",
                                  name: "Rajan Kumar Gupta",
                                  join_by: "1371",
                                  wallet: "0.00",
                                  roi_comission: "0.00",
                                  phone: "7800250217",
                                  datetime: "2024-11-25 11:54:32",
                                  level: "7",
                                  self_payin: "50000",
                                  subordinate_payin: 50000,
                                  this_month_payin: 0,
                                  children: [
                                    {
                                      user_id: "6238",
                                      name: "Vikash Maddheshiya",
                                      join_by: "6821",
                                      wallet: "0.00",
                                      roi_comission: "0.00",
                                      phone: "7880813737",
                                      datetime: "2024-12-01 20:55:58",
                                      level: "8",
                                      self_payin: 0,
                                      subordinate_payin: 50000,
                                      this_month_payin: 0,
                                      children: [
                                        {
                                          user_id: "244",
                                          name: "Vikash kumar",
                                          join_by: "6238",
                                          wallet: "0.00",
                                          roi_comission: "0.00",
                                          phone: "9569613877",
                                          datetime: "2024-12-01 21:38:05",
                                          level: "9",
                                          self_payin: "50000",
                                          subordinate_payin: 0,
                                          this_month_payin: 0,
                                          children: [],
                                        },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      user_id: "2741",
                      name: "Shubham",
                      join_by: "2839",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "9170396404",
                      datetime: "2024-11-20 14:23:14",
                      level: "4",
                      self_payin: "170000",
                      subordinate_payin: 1660000,
                      this_month_payin: 0,
                      children: [
                        {
                          user_id: "5667",
                          name: "Vivek Tiwari",
                          join_by: "2741",
                          wallet: "0.00",
                          roi_comission: "0.00",
                          phone: "9984788431",
                          datetime: "2024-11-21 22:43:43",
                          level: "5",
                          self_payin: "50000",
                          subordinate_payin: 100000,
                          this_month_payin: 0,
                          children: [
                            {
                              user_id: "4438",
                              name: "Bipin Tiwari",
                              join_by: "5667",
                              wallet: "0.00",
                              roi_comission: "0.00",
                              phone: "8052784532",
                              datetime: "2024-11-21 22:44:52",
                              level: "6",
                              self_payin: "100000",
                              subordinate_payin: 0,
                              this_month_payin: 0,
                              children: [],
                            },
                          ],
                        },
                        {
                          user_id: "5421",
                          name: "Akash Patel",
                          join_by: "2741",
                          wallet: "0.00",
                          roi_comission: "0.00",
                          phone: "7565958377",
                          datetime: "2024-12-04 11:22:26",
                          level: "5",
                          self_payin: "80000",
                          subordinate_payin: 0,
                          this_month_payin: 0,
                          children: [],
                        },
                        {
                          user_id: "5561",
                          name: "Saurabh Jaiswal",
                          join_by: "2741",
                          wallet: "0.00",
                          roi_comission: "0.00",
                          phone: "9838402562",
                          datetime: "2024-12-18 12:31:18",
                          level: "5",
                          self_payin: "300000",
                          subordinate_payin: 1130000,
                          this_month_payin: 0,
                          children: [
                            {
                              user_id: "1225",
                              name: "Kohinoor",
                              join_by: "5561",
                              wallet: "0.00",
                              roi_comission: "0.00",
                              phone: "9721905874",
                              datetime: "2024-12-21 15:51:14",
                              level: "6",
                              self_payin: "20000",
                              subordinate_payin: 510000,
                              this_month_payin: 0,
                              children: [
                                {
                                  user_id: "7866",
                                  name: "Shriprakash Tiwari Ji",
                                  join_by: "1225",
                                  wallet: "0.00",
                                  roi_comission: "0.00",
                                  phone: "9455582627",
                                  datetime: "2024-12-26 11:40:36",
                                  level: "7",
                                  self_payin: "10000",
                                  subordinate_payin: 500000,
                                  this_month_payin: 0,
                                  children: [
                                    {
                                      user_id: "360",
                                      name: "Shiva",
                                      join_by: "7866",
                                      wallet: "0.00",
                                      roi_comission: "0.00",
                                      phone: "8127138009",
                                      datetime: "2024-12-21 19:04:39",
                                      level: "8",
                                      self_payin: 0,
                                      subordinate_payin: 500000,
                                      this_month_payin: 0,
                                      children: [
                                        {
                                          user_id: "1327",
                                          name: "Amrit Jaiswal ",
                                          join_by: "360",
                                          wallet: "0.00",
                                          roi_comission: "0.00",
                                          phone: "9565920003",
                                          datetime: "2025-01-03 20:24:18",
                                          level: "9",
                                          self_payin: "330000",
                                          subordinate_payin: 170000,
                                          this_month_payin: "660000",
                                          children: [
                                            {
                                              user_id: "5149",
                                              name: "Shubham Ji",
                                              join_by: "1327",
                                              wallet: "0.00",
                                              roi_comission: "10.00",
                                              phone: "9628884228",
                                              datetime: "2025-01-02 11:28:44",
                                              level: "10",
                                              self_payin: "50000",
                                              subordinate_payin: 120000,
                                              this_month_payin: "200000",
                                              children: [
                                                {
                                                  user_id: "4979",
                                                  name: "Raju Jaiswal ",
                                                  join_by: "5149",
                                                  wallet: "0.00",
                                                  roi_comission: "0.00",
                                                  phone: "9264936344",
                                                  datetime: "2025-01-03 20:25:38",
                                                  level: "11",
                                                  self_payin: "100000",
                                                  subordinate_payin: 20000,
                                                  this_month_payin: "200000",
                                                  children: [
                                                    {
                                                      user_id: "8389",
                                                      name: "Yuvraj ji",
                                                      join_by: "4979",
                                                      wallet: "0.00",
                                                      roi_comission: "0.00",
                                                      phone: "9919118751",
                                                      datetime:
                                                        "2025-01-16 17:55:31",
                                                      level: "12",
                                                      self_payin: "20000",
                                                      subordinate_payin: 0,
                                                      this_month_payin: "20000",
                                                      children: [],
                                                    },
                                                  ],
                                                },
                                              ],
                                            },
                                          ],
                                        },
                                      ],
                                    },
                                    {
                                      user_id: "1720",
                                      name: "Ramprakash Tiwari",
                                      join_by: "7866",
                                      wallet: "0.00",
                                      roi_comission: "0.00",
                                      phone: "8009498787",
                                      datetime: "2025-01-07 16:52:41",
                                      level: "8",
                                      self_payin: 0,
                                      subordinate_payin: 0,
                                      this_month_payin: 0,
                                      children: [],
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              user_id: "6634",
                              name: "Neeraj Kumar ",
                              join_by: "5561",
                              wallet: "0.00",
                              roi_comission: "0.00",
                              phone: "7290830194",
                              datetime: "2024-12-24 09:59:22",
                              level: "6",
                              self_payin: "10000",
                              subordinate_payin: 590000,
                              this_month_payin: 0,
                              children: [
                                {
                                  user_id: "9021",
                                  name: "Saroj Devi",
                                  join_by: "6634",
                                  wallet: "0.00",
                                  roi_comission: "0.00",
                                  phone: "9670326788",
                                  datetime: "2024-12-28 18:59:53",
                                  level: "7",
                                  self_payin: "200000",
                                  subordinate_payin: 390000,
                                  this_month_payin: 0,
                                  children: [
                                    {
                                      user_id: "5912",
                                      name: "Malya Jaiswal Ji",
                                      join_by: "9021",
                                      wallet: "0.00",
                                      roi_comission: "0.00",
                                      phone: "9696788218",
                                      datetime: "2024-12-28 10:27:06",
                                      level: "8",
                                      self_payin: "10000",
                                      subordinate_payin: 380000,
                                      this_month_payin: "20000",
                                      children: [
                                        {
                                          user_id: "224",
                                          name: "Mukul Jaiswal",
                                          join_by: "5912",
                                          wallet: "0.00",
                                          roi_comission: "0.00",
                                          phone: "9554078784",
                                          datetime: "2024-11-21 15:51:36",
                                          level: "9",
                                          self_payin: "150000",
                                          subordinate_payin: 230000,
                                          this_month_payin: "150000",
                                          children: [
                                            {
                                              user_id: "5131",
                                              name: "Anuj Verma Ji",
                                              join_by: "224",
                                              wallet: "0.00",
                                              roi_comission: "0.00",
                                              phone: "7007901513",
                                              datetime: "2025-01-11 12:50:49",
                                              level: "10",
                                              self_payin: 0,
                                              subordinate_payin: 0,
                                              this_month_payin: 0,
                                              children: [],
                                            },
                                            {
                                              user_id: "1272",
                                              name: "Mukul Ji",
                                              join_by: "224",
                                              wallet: "0.00",
                                              roi_comission: "0.00",
                                              phone: "9598111475",
                                              datetime: "2025-01-14 13:29:28",
                                              level: "10",
                                              self_payin: "50000",
                                              subordinate_payin: 180000,
                                              this_month_payin: "50000",
                                              children: [
                                                {
                                                  user_id: "4158",
                                                  name: "Nishant Yadav",
                                                  join_by: "1272",
                                                  wallet: "0.00",
                                                  roi_comission: "0.00",
                                                  phone: "9795373841",
                                                  datetime: "2025-01-14 13:38:32",
                                                  level: "11",
                                                  self_payin: "180000",
                                                  subordinate_payin: 0,
                                                  this_month_payin: "180000",
                                                  children: [],
                                                },
                                              ],
                                            },
                                          ],
                                        },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  user_id: "3700",
                  name: "Avinash Chaurasiya",
                  join_by: "9237",
                  wallet: "0.00",
                  roi_comission: "0.00",
                  phone: "7398709750",
                  datetime: "2024-11-20 14:17:39",
                  level: "3",
                  self_payin: "20000",
                  subordinate_payin: 2340000,
                  this_month_payin: 0,
                  children: [
                    {
                      user_id: "2337",
                      name: "Adarsh Singh",
                      join_by: "3700",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "9140074531",
                      datetime: "2024-11-20 14:30:02",
                      level: "4",
                      self_payin: "50000",
                      subordinate_payin: 2030000,
                      this_month_payin: 0,
                      children: [
                        {
                          user_id: "6150",
                          name: "Susheel Singh",
                          join_by: "2337",
                          wallet: "50000.00",
                          roi_comission: "0.00",
                          phone: "7652063119",
                          datetime: "2024-11-20 14:33:22",
                          level: "5",
                          self_payin: "60000",
                          subordinate_payin: 1280000,
                          this_month_payin: 0,
                          children: [
                            {
                              user_id: "1712",
                              name: "Shweta Patel ",
                              join_by: "6150",
                              wallet: "0.00",
                              roi_comission: "0.00",
                              phone: "6386232902",
                              datetime: "2024-11-20 14:35:27",
                              level: "6",
                              self_payin: "50000",
                              subordinate_payin: 570000,
                              this_month_payin: 0,
                              children: [
                                {
                                  user_id: "410",
                                  name: "Rituraj Singh",
                                  join_by: "1712",
                                  wallet: "0.00",
                                  roi_comission: "0.00",
                                  phone: "9140171268",
                                  datetime: "2024-12-12 11:04:54",
                                  level: "7",
                                  self_payin: "200000",
                                  subordinate_payin: 370000,
                                  this_month_payin: 0,
                                  children: [
                                    {
                                      user_id: "5964",
                                      name: "Aryan Singh",
                                      join_by: "410",
                                      wallet: "0.00",
                                      roi_comission: "0.00",
                                      phone: "7398691110",
                                      datetime: "2024-11-20 14:34:35",
                                      level: "8",
                                      self_payin: "50000",
                                      subordinate_payin: 250000,
                                      this_month_payin: 0,
                                      children: [
                                        {
                                          user_id: "8042",
                                          name: "Abhinav Singh",
                                          join_by: "5964",
                                          wallet: "0.00",
                                          roi_comission: "0.00",
                                          phone: "7237930837",
                                          datetime: "2024-11-21 16:29:12",
                                          level: "9",
                                          self_payin: "90000",
                                          subordinate_payin: 160000,
                                          this_month_payin: 0,
                                          children: [
                                            {
                                              user_id: "5584",
                                              name: "Vivek Singh",
                                              join_by: "8042",
                                              wallet: "0.00",
                                              roi_comission: "0.00",
                                              phone: "6389370756",
                                              datetime: "2024-12-16 13:17:02",
                                              level: "10",
                                              self_payin: "30000",
                                              subordinate_payin: 130000,
                                              this_month_payin: 0,
                                              children: [
                                                {
                                                  user_id: "6321",
                                                  name: "Abhishek Tiwari",
                                                  join_by: "5584",
                                                  wallet: "0.00",
                                                  roi_comission: "0.00",
                                                  phone: "8858641381",
                                                  datetime: "2025-01-11 15:56:57",
                                                  level: "11",
                                                  self_payin: "100000",
                                                  subordinate_payin: 30000,
                                                  this_month_payin: "100000",
                                                  children: [
                                                    {
                                                      user_id: "9433",
                                                      name: "Anurag Singh",
                                                      join_by: "6321",
                                                      wallet: "0.00",
                                                      roi_comission: "0.00",
                                                      phone: "8576882858",
                                                      datetime:
                                                        "2025-01-11 16:59:42",
                                                      level: "12",
                                                      self_payin: "30000",
                                                      subordinate_payin: 0,
                                                      this_month_payin: "30000",
                                                      children: [],
                                                    },
                                                  ],
                                                },
                                              ],
                                            },
                                          ],
                                        },
                                      ],
                                    },
                                    {
                                      user_id: "8180",
                                      name: "Suman",
                                      join_by: "410",
                                      wallet: "0.00",
                                      roi_comission: "0.00",
                                      phone: "8115192441",
                                      datetime: "2025-01-05 19:16:59",
                                      level: "8",
                                      self_payin: "70000",
                                      subordinate_payin: 0,
                                      this_month_payin: "70000",
                                      children: [],
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              user_id: "459",
                              name: "Shailesh Devi",
                              join_by: "6150",
                              wallet: "0.00",
                              roi_comission: "0.00",
                              phone: "8354924003",
                              datetime: "2024-12-17 18:21:42",
                              level: "6",
                              self_payin: "70000",
                              subordinate_payin: 590000,
                              this_month_payin: 0,
                              children: [
                                {
                                  user_id: "3608",
                                  name: "Mukesh Gupta",
                                  join_by: "459",
                                  wallet: "0.00",
                                  roi_comission: "0.00",
                                  phone: "9517197032",
                                  datetime: "2024-11-29 12:30:25",
                                  level: "7",
                                  self_payin: "200000",
                                  subordinate_payin: 390000,
                                  this_month_payin: 0,
                                  children: [
                                    {
                                      user_id: "7426",
                                      name: "Vishal Singh",
                                      join_by: "3608",
                                      wallet: "0.00",
                                      roi_comission: "9000.00",
                                      phone: "8874467618",
                                      datetime: "2024-12-03 10:16:12",
                                      level: "8",
                                      self_payin: "100000",
                                      subordinate_payin: 290000,
                                      this_month_payin: 0,
                                      children: [
                                        {
                                          user_id: "2902",
                                          name: "Amit Singh",
                                          join_by: "7426",
                                          wallet: "0.00",
                                          roi_comission: "0.00",
                                          phone: "6393642597",
                                          datetime: "2024-12-02 18:28:56",
                                          level: "9",
                                          self_payin: "20000",
                                          subordinate_payin: 270000,
                                          this_month_payin: 0,
                                          children: [
                                            {
                                              user_id: "4533",
                                              name: "Sudhanshu Singh ",
                                              join_by: "2902",
                                              wallet: "0.00",
                                              roi_comission: "0.00",
                                              phone: "8881944538",
                                              datetime: "2024-12-09 12:17:27",
                                              level: "10",
                                              self_payin: "20000",
                                              subordinate_payin: 250000,
                                              this_month_payin: 0,
                                              children: [
                                                {
                                                  user_id: "6981",
                                                  name: "Raghuveer Chaurasiya",
                                                  join_by: "4533",
                                                  wallet: "0.00",
                                                  roi_comission: "0.00",
                                                  phone: "7292927435",
                                                  datetime: "2024-12-24 11:26:07",
                                                  level: "11",
                                                  self_payin: "30000",
                                                  subordinate_payin: 220000,
                                                  this_month_payin: 0,
                                                  children: [
                                                    {
                                                      user_id: "871",
                                                      name: "Amit Patel",
                                                      join_by: "6981",
                                                      wallet: "0.00",
                                                      roi_comission: "0.00",
                                                      phone: "7705933816",
                                                      datetime:
                                                        "2025-01-07 00:18:13",
                                                      level: "12",
                                                      self_payin: "10000",
                                                      subordinate_payin: 210000,
                                                      this_month_payin: "10000",
                                                      children: [
                                                        {
                                                          user_id: "39",
                                                          name: "Sandhya Chaurasiya",
                                                          join_by: "871",
                                                          wallet: "0.00",
                                                          roi_comission: "0.00",
                                                          phone: "9026401817",
                                                          datetime:
                                                            "2025-01-07 14:19:10",
                                                          level: "13",
                                                          self_payin: "10000",
                                                          subordinate_payin: 200000,
                                                          this_month_payin:
                                                            "10000",
                                                          children: [
                                                            {
                                                              user_id: "4155",
                                                              name: "Harsh Giri",
                                                              join_by: "39",
                                                              wallet: "0.00",
                                                              roi_comission:
                                                                "0.00",
                                                              phone: "7234856297",
                                                              datetime:
                                                                "2025-01-07 23:05:44",
                                                              level: "14",
                                                              self_payin:
                                                                "100000",
                                                              subordinate_payin: 100000,
                                                              this_month_payin:
                                                                "100000",
                                                              children: [
                                                                {
                                                                  user_id: "6776",
                                                                  name: "Manish Singh",
                                                                  join_by: "4155",
                                                                  wallet: "0.00",
                                                                  roi_comission:
                                                                    "0.00",
                                                                  phone:
                                                                    "9648039075",
                                                                  datetime:
                                                                    "2025-01-07 23:09:11",
                                                                  level: "15",
                                                                  self_payin:
                                                                    "100000",
                                                                  subordinate_payin: 0,
                                                                  this_month_payin:
                                                                    "100000",
                                                                  children: [],
                                                                },
                                                              ],
                                                            },
                                                          ],
                                                        },
                                                      ],
                                                    },
                                                  ],
                                                },
                                              ],
                                            },
                                          ],
                                        },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          user_id: "4660",
                          name: "Grijesh Singh",
                          join_by: "2337",
                          wallet: "0.00",
                          roi_comission: "0.00",
                          phone: "8795772655",
                          datetime: "2024-11-27 00:34:11",
                          level: "5",
                          self_payin: "330000",
                          subordinate_payin: 360000,
                          this_month_payin: "10000",
                          children: [
                            {
                              user_id: "3791",
                              name: "Nikki Singh",
                              join_by: "4660",
                              wallet: "0.00",
                              roi_comission: "0.00",
                              phone: "8127906275",
                              datetime: "2025-01-05 11:18:28",
                              level: "6",
                              self_payin: "20000",
                              subordinate_payin: 230000,
                              this_month_payin: "20000",
                              children: [
                                {
                                  user_id: "3739",
                                  name: "Apurv",
                                  join_by: "3791",
                                  wallet: "0.00",
                                  roi_comission: "0.00",
                                  phone: "8960721756",
                                  datetime: "2025-01-07 20:16:04",
                                  level: "7",
                                  self_payin: "20000",
                                  subordinate_payin: 210000,
                                  this_month_payin: "20000",
                                  children: [
                                    {
                                      user_id: "6757",
                                      name: "Pawan Singh",
                                      join_by: "3739",
                                      wallet: "0.00",
                                      roi_comission: "0.00",
                                      phone: "7081068928",
                                      datetime: "2024-12-26 18:06:40",
                                      level: "8",
                                      self_payin: "10000",
                                      subordinate_payin: 200000,
                                      this_month_payin: 0,
                                      children: [
                                        {
                                          user_id: "9964",
                                          name: "Shivshankar Gupta",
                                          join_by: "6757",
                                          wallet: "0.00",
                                          roi_comission: "0.00",
                                          phone: "9838861865",
                                          datetime: "2024-12-16 15:03:10",
                                          level: "9",
                                          self_payin: "200000",
                                          subordinate_payin: 0,
                                          this_month_payin: "200000",
                                          children: [],
                                        },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                            {
                              user_id: "7235",
                              name: "Saripf khan",
                              join_by: "4660",
                              wallet: "0.00",
                              roi_comission: "0.00",
                              phone: "8826820575",
                              datetime: "2025-01-08 20:02:46",
                              level: "6",
                              self_payin: "10000",
                              subordinate_payin: 100000,
                              this_month_payin: "10000",
                              children: [
                                {
                                  user_id: "2051",
                                  name: "Madan Gupta",
                                  join_by: "7235",
                                  wallet: "0.00",
                                  roi_comission: "0.00",
                                  phone: "9648080464",
                                  datetime: "2025-01-10 19:33:58",
                                  level: "7",
                                  self_payin: "100000",
                                  subordinate_payin: 0,
                                  this_month_payin: "100000",
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      user_id: "9388",
                      name: "Diwakar Jaiswal ",
                      join_by: "3700",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "9838177328",
                      datetime: "2024-11-20 14:31:55",
                      level: "4",
                      self_payin: "60000",
                      subordinate_payin: 200000,
                      this_month_payin: 0,
                      children: [
                        {
                          user_id: "5614",
                          name: "Anjali Jaiswal ",
                          join_by: "9388",
                          wallet: "0.00",
                          roi_comission: "0.00",
                          phone: "9889666768",
                          datetime: "2024-11-20 14:36:19",
                          level: "5",
                          self_payin: "100000",
                          subordinate_payin: 0,
                          this_month_payin: 0,
                          children: [],
                        },
                        {
                          user_id: "5604",
                          name: "Bipin",
                          join_by: "9388",
                          wallet: "0.00",
                          roi_comission: "0.00",
                          phone: "9889009081",
                          datetime: "2024-11-20 14:37:57",
                          level: "5",
                          self_payin: "100000",
                          subordinate_payin: 0,
                          this_month_payin: 0,
                          children: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              user_id: "5742",
              name: "Prakhar Tripathi",
              join_by: "4133",
              wallet: "0.00",
              roi_comission: "0.00",
              phone: "7318114991",
              datetime: "2024-11-20 14:42:11",
              level: "2",
              self_payin: 0,
              subordinate_payin: 1680000,
              this_month_payin: 0,
              children: [
                {
                  user_id: "9169",
                  name: "Anunay Sharma ",
                  join_by: "5742",
                  wallet: "0.00",
                  roi_comission: "0.00",
                  phone: "9870559330",
                  datetime: "2024-11-20 14:46:11",
                  level: "3",
                  self_payin: "500000",
                  subordinate_payin: 1180000,
                  this_month_payin: 0,
                  children: [
                    {
                      user_id: "9706",
                      name: "Antima Sharma ",
                      join_by: "9169",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "7291918906",
                      datetime: "2024-11-20 14:47:50",
                      level: "4",
                      self_payin: "390000",
                      subordinate_payin: 400000,
                      this_month_payin: "30000",
                      children: [
                        {
                          user_id: "3816",
                          name: "Arohi Sharma",
                          join_by: "9706",
                          wallet: "0.00",
                          roi_comission: "0.00",
                          phone: "8368702595",
                          datetime: "2025-01-08 09:56:11",
                          level: "5",
                          self_payin: "250000",
                          subordinate_payin: 150000,
                          this_month_payin: "250000",
                          children: [
                            {
                              user_id: "7253",
                              name: "Rahul vishwakarma",
                              join_by: "3816",
                              wallet: "0.00",
                              roi_comission: "0.00",
                              phone: "7235834139",
                              datetime: "2024-12-11 10:59:02",
                              level: "6",
                              self_payin: "150000",
                              subordinate_payin: 0,
                              this_month_payin: 0,
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      user_id: "2619",
                      name: "Anunay",
                      join_by: "9169",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "9628324230",
                      datetime: "2024-11-20 14:49:21",
                      level: "4",
                      self_payin: "390000",
                      subordinate_payin: 0,
                      this_month_payin: "250000",
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              user_id: "86",
              name: "Abhishek Koiri",
              join_by: "4133",
              wallet: "0.00",
              roi_comission: "0.00",
              phone: "8768832500",
              datetime: "2024-11-20 14:43:40",
              level: "2",
              self_payin: 0,
              subordinate_payin: 1430000,
              this_month_payin: 0,
              children: [
                {
                  user_id: "8672",
                  name: "Sarvar ALi",
                  join_by: "86",
                  wallet: "0.00",
                  roi_comission: "0.00",
                  phone: "9565533093",
                  datetime: "2024-11-20 14:44:46",
                  level: "3",
                  self_payin: 0,
                  subordinate_payin: 150000,
                  this_month_payin: 0,
                  children: [
                    {
                      user_id: "6925",
                      name: "Adv Raheem",
                      join_by: "8672",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "8957515154",
                      datetime: "2024-11-27 10:40:39",
                      level: "4",
                      self_payin: "100000",
                      subordinate_payin: 0,
                      this_month_payin: "10000",
                      children: [],
                    },
                    {
                      user_id: "8101",
                      name: "Sachin Yadav",
                      join_by: "8672",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "7800418427",
                      datetime: "2025-01-21 19:25:32",
                      level: "4",
                      self_payin: "50000",
                      subordinate_payin: 0,
                      this_month_payin: "50000",
                      children: [],
                    },
                  ],
                },
                {
                  user_id: "2810",
                  name: "Sachin Yadav",
                  join_by: "86",
                  wallet: "0.00",
                  roi_comission: "0.00",
                  phone: "9369593501",
                  datetime: "2024-11-21 15:44:50",
                  level: "3",
                  self_payin: 0,
                  subordinate_payin: 1280000,
                  this_month_payin: 0,
                  children: [
                    {
                      user_id: "7343",
                      name: "Shatrudhan Yadav",
                      join_by: "2810",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "9565100203",
                      datetime: "2024-11-21 15:49:32",
                      level: "4",
                      self_payin: "150000",
                      subordinate_payin: 0,
                      this_month_payin: "50000",
                      children: [],
                    },
                    {
                      user_id: "6184",
                      name: "Shridhar Pathak",
                      join_by: "2810",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "9838364161",
                      datetime: "2024-12-13 16:56:05",
                      level: "4",
                      self_payin: "50000",
                      subordinate_payin: 530000,
                      this_month_payin: 0,
                      children: [
                        {
                          user_id: "1947",
                          name: "Nandani Devi",
                          join_by: "6184",
                          wallet: "0.00",
                          roi_comission: "0.00",
                          phone: "9838985022",
                          datetime: "2024-12-13 16:58:15",
                          level: "5",
                          self_payin: "350000",
                          subordinate_payin: 0,
                          this_month_payin: 0,
                          children: [],
                        },
                        {
                          user_id: "6192",
                          name: "Pathak ji",
                          join_by: "6184",
                          wallet: "0.00",
                          roi_comission: "0.00",
                          phone: "9838364151",
                          datetime: "2024-12-19 22:02:45",
                          level: "5",
                          self_payin: "180000",
                          subordinate_payin: 0,
                          this_month_payin: "80000",
                          children: [],
                        },
                      ],
                    },
                    {
                      user_id: "3575",
                      name: "Mukesh Kumar Yadav",
                      join_by: "2810",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "8416913194",
                      datetime: "2024-12-13 17:22:44",
                      level: "4",
                      self_payin: "180000",
                      subordinate_payin: 0,
                      this_month_payin: "80000",
                      children: [],
                    },
                    {
                      user_id: "991",
                      name: "Ritesh Singh",
                      join_by: "2810",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "9565302798",
                      datetime: "2024-12-18 13:10:35",
                      level: "4",
                      self_payin: "30000",
                      subordinate_payin: 0,
                      this_month_payin: "20000",
                      children: [],
                    },
                    {
                      user_id: "9149",
                      name: "RAM PRIT CHAURASIYA",
                      join_by: "2810",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "7081401971",
                      datetime: "2024-12-24 20:42:59",
                      level: "4",
                      self_payin: "300000",
                      subordinate_payin: 0,
                      this_month_payin: 0,
                      children: [],
                    },
                    {
                      user_id: "512",
                      name: "Sachin Ji",
                      join_by: "2810",
                      wallet: "0.00",
                      roi_comission: "0.00",
                      phone: "7705858415",
                      datetime: "2025-01-15 18:36:44",
                      level: "4",
                      self_payin: "40000",
                      subordinate_payin: 0,
                      this_month_payin: "40000",
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              user_id: "6210",
              name: "Madhusudan Mishra",
              join_by: "4133",
              wallet: "0.00",
              roi_comission: "0.00",
              phone: "8624918239",
              datetime: "2024-11-21 20:27:54",
              level: "2",
              self_payin: "100000",
              subordinate_payin: 0,
              this_month_payin: 0,
              children: [],
            },
            {
              user_id: "8040",
              name: "Rajendra Ojha",
              join_by: "4133",
              wallet: "600000.00",
              roi_comission: "0.00",
              phone: "9811960026",
              datetime: "2024-11-21 20:31:19",
              level: "2",
              self_payin: "1100000",
              subordinate_payin: 600000,
              this_month_payin: 0,
              children: [
                {
                  user_id: "7641",
                  name: "Neha Tiwari",
                  join_by: "8040",
                  wallet: "0.00",
                  roi_comission: "0.00",
                  phone: "8178281353",
                  datetime: "2024-12-16 12:29:41",
                  level: "3",
                  self_payin: "600000",
                  subordinate_payin: 0,
                  this_month_payin: 0,
                  children: [],
                },
              ],
            },
            {
              user_id: "4707",
              name: "Vishal Yadav",
              join_by: "4133",
              wallet: "200000.00",
              roi_comission: "0.00",
              phone: "9628344413",
              datetime: "2024-11-21 20:33:07",
              level: "2",
              self_payin: "200000",
              subordinate_payin: 0,
              this_month_payin: 0,
              children: [],
            },
            {
              user_id: "3734",
              name: "Rishu Gupta",
              join_by: "4133",
              wallet: "0.00",
              roi_comission: "0.00",
              phone: "7408776191",
              datetime: "2024-11-21 20:34:11",
              level: "2",
              self_payin: "10000",
              subordinate_payin: 0,
              this_month_payin: 0,
              children: [],
            },
            {
              user_id: "9141",
              name: "khan",
              join_by: "4133",
              wallet: "0.00",
              roi_comission: "0.00",
              phone: "8081851064",
              datetime: "2024-11-21 21:32:05",
              level: "2",
              self_payin: "70000",
              subordinate_payin: 100000,
              this_month_payin: 0,
              children: [
                {
                  user_id: "1334",
                  name: "Mohammad Ali",
                  join_by: "9141",
                  wallet: "0.00",
                  roi_comission: "0.00",
                  phone: "7380446354",
                  datetime: "2024-11-21 21:36:42",
                  level: "3",
                  self_payin: "100000",
                  subordinate_payin: 0,
                  this_month_payin: 0,
                  children: [],
                },
              ],
            },
            {
              user_id: "2191",
              name: "Sudhanshu Rathore",
              join_by: "4133",
              wallet: "0.00",
              roi_comission: "0.00",
              phone: "8881055456",
              datetime: "2024-12-21 19:00:02",
              level: "2",
              self_payin: 0,
              subordinate_payin: 0,
              this_month_payin: 0,
              children: [],
            },
          ],
        },
        {
          user_id: "5826",
          name: "Foundercodetesting",
          join_by: "111",
          wallet: "0.00",
          roi_comission: "0.00",
          phone: "7705018444",
          datetime: "2025-01-19 13:45:33",
          level: "1",
          self_payin: 0,
          subordinate_payin: 0,
          this_month_payin: 0,
          children: [],
        },
      ],
    },
  ];